### ISSUE TITLE
Omnibear incorrectly reports page liked successfully

### ISSUE THREAD

**Issue by dougbeal** [keithjgrant/omnibear#74] opened 2018-07-08 01:09 UTC
&gt; {
&gt;
&gt;  **Warning** : in_array() expects parameter 2 to be array, null given in **/var/www/html/wp-content/plugins/micropub/micropub.php** on line **265**
&gt;
&gt; **Warning** : in_array() expects parameter 2 to be array, null given in **/var/www/html/wp-content/plugins/micropub/micropub.php** on line **268**
&gt;
&gt; **Warning** : Cannot modify header information – headers already sent by (output started at /var/www/html/wp-content/plugins/micropub/micropub.php:265) in **/var/www/html/wp-content/plugins/micropub/micropub.php** on line **1225**
&gt;  {“error”:”insufficient_scope”,”error_description”:”scope insufficient to create posts”}:
&gt;  }

(Originally published at: https://crw.moe/b/U0)

**Comment by dougbeal** [comment] 2018-07-08 01:55
&gt; {
&gt;
&gt;  **Warning** : in_array() expects parameter 2 to be array, null given in **/var/www/html/wp-content/plugins/micropub/micropub.php** on line **265**
&gt;
&gt; **Warning** : in_array() expects parameter 2 to be array, null given in **/var/www/html/wp-content/plugins/micropub/micropub.php** on line **268**
&gt;
&gt; **Warning** : Cannot modify header information – headers already sent by (output started at /var/www/html/wp-content/plugins/micropub/micropub.php:265) in **/var/www/html/wp-content/plugins/micropub/micropub.php** on line **1225**
&gt;  {“error”:”insufficient_scope”,”error_description”:”scope insufficient to create posts”}:
&gt;  }

(Originally published at: https://crw.moe/b/U0)

**Comment by keithjgrant** [comment] 2018-08-22 17:25
I believe we finally have a workaround for this, which I will get added into the next version. The core issue is in the wordpress plugin and is being addressed seperately (https://github.com/snarfed/wordpress-micropub/issues/133)

**Comment by keithjgrant** [comment] 2018-08-22 17:27
Closing as duplicate of #20

**Closed by keithjgrant** 2018-08-22 17:27 UTC
